openapi: 3.0.3

info:
  title: Merchant Service API
  description: REST API for managing merchants and merchant transactions
  version: 1.0.0
servers:
  - url: /_merchant
paths:
  /merchants:
    post:
      summary: Register a new merchant
      description: Registers a new merchant and returns the created merchant
      tags:
        - Merchants
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Merchant'
      responses:
        '201':
          description: Merchant successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Merchant'
        '400':
          description: Merchant registration failed
          content:
              text/plain:
                schema:
                  type: string
        '500':
          description: Internal server error

  /merchants/{merchantId}:
    get:
      summary: Get merchant by ID
      description: Retrieves a merchant by their ID
      tags:
        - Merchants
      parameters:
        - name: merchantId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Merchant found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Merchant'
        '404':
          description: Merchant not found

    delete:
      summary: Delete merchant
      description: Deletes a merchant by their ID
      tags:
        - Merchants
      parameters:
        - name: merchantId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Merchant successfully deleted
        '404':
          description: Merchant not found

  /merchants/{merchantId}/reports:
    get:
      summary: Get merchant transaction report
      description: Returns all transactions associated with a merchant
      tags:
        - Merchants
      parameters:
        - name: merchantId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Merchant transaction report retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MerchantTransaction'
       

  /merchants/{merchantId}/payments:
    post:
      summary: Register a merchant transaction
      description: Registers a new transaction for a merchant
      tags:
        - Merchants
      parameters:
        - name: merchantId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MerchantTransaction'
      responses:
        '201':
          description: Transaction successfully registered
        '400':
          description: Invalid transaction data
        '404':
          description: Merchant not found

components:
  schemas:
    Merchant:
      type: object
      description: Represents a merchant
      properties:
        firstName:
          type: string
          example: "Alice"
        lastName:
          type: string
          example: "Smith"
        cpr:
          type: string
          example: "654321-0987"
        bankAccountUuid:
          type: string
          example: "bank-uuid-789"
        dtupayUuid:
          type: string
          example: "dtupay-uuid-321"
      required:
        - firstName
        - lastName
        - cpr
        - bankAccountUuid
        - dtupayUuid

    MerchantTransaction:
      type: object
      description: Represents a transaction initiated by a merchant
      properties:
        tokenId:
          type: string
          example: "token-xyz456"
        merchantId:
          type: string
          example: "merchant-99"
        amount:
          type: string
          example: "150.00"
        transactionId:
          type: string
          example: "tx-456"
        timestamp:
          type: string
          example: "2024-03-18T15:45:00Z"
      required:
        - tokenId
        - merchantId
        - amount
        - transactionId
        - timestamp
